#' Resample likelihood rasters to common resolution/extent
#' 
#' @param L.rasters list of individual likelihood rasters generated by calc 
#'   functions
#' @param L.res raster or raster brick indicating desired output resolution of
#'   all likelihood rasters.
#' @param aggregate is logical indicating whether you want the function to try
#'   to aggregate grid cells to generate a coarse raster for parameter
#'   estimation that ends up around resolution of 1deg. Otherwise, the coarse
#'   grid outputs will be based on the max resolution of inputs rasters.
#'   
#' @return a list of all resampled likelihood rasters and g, the common grid
#' @export
#' 

resample.grid <- function(L.rasters, L.res, aggregate=FALSE, cellAgg=NULL){
  
  start.t <- Sys.time()
  
  L.rasters.old <- L.rasters
  
  for (i in 1:length(L.rasters)){
    r <- L.rasters[[i]]
    
    if (i == 1){
      resol <- raster::res(r)[1]
    } else{
      resol <- c(resol, raster::res(r)[1])
    }
    
    t <- Sys.time()
    r <- raster::resample(r, L.res)
    print(Sys.time() - t)
    r[r == 0] <- NA
    L.rasters[[i]] <- r

  }
  
  print(resol)
  
  L.mle.res <- L.rasters.old[which(resol == max(resol))][[1]]
  
  if(aggregate & raster::res(L.mle.res)[1] < 0.3){
    if(is.null(cellAgg)){
      cellAgg <- 2
      print(paste('cellAgg input is not specified. Assuming a default value of ', cellAgg,'...', sep=''))
    } 
    L.mle.res <- raster::aggregate(L.mle.res, cellAgg)
  }
  
  g <- HMMoce:::setup.grid.raster(L.res)
  g.mle <- HMMoce:::setup.grid.raster(L.mle.res)
  
  print(paste('Raster resample took ', Sys.time() - start.t, '.'))
  
  list(L.rasters, L.mle.res = L.mle.res, g = g, g.mle = g.mle)
  
}
